### ISSUE TITLE
Upgrade protobuf v3.6.1 to v3.12.3

### ISSUE THREAD

**Issue by again4you** [nnstreamer/nnstreamer#2411]
### Goal
* ~~upgrade protobuf v3.6.1 to v3.8.~~
* upgrade protobuf v3.6.1 to v.3.12.3

Because of latest version of Tensorflow, we are going to upgrade protobuf `v3.6.1` to `v3.12.3`.

### Progress status

- [x] Tizen Unified: tizen-unified_20200707.1
- [x] Ubuntu Launcupad 

### Issue

However, there are some issue for Caffe2 / Pytorch. 
IIRC, Caffe2 use it's own internal protobuf but Pytorch does not. 
(@kparichay alsl agreed with my oninion.)

I tested 2 cases on [PPA Staging Server](https://launchpad.net/~nnstreamer/+archive/ubuntu/ppa-build-test). 

#### Test case 1
* Caffe2 / Pytorch internally use protobuf v3.8 (force archiving)
* Protobuf v3.6.1

When buinding caffe2 filter of nnstreamer, compile time error occurs as below.
The main reason for this error is 'incompatible with your Protocol Buffer headers'

```bash
FAILED: ext/nnstreamer/tensor_filter/584bea7@@nnstreamer_filter_caffe2@sha/tensor_filter_caffe2.cc.o 
c++ -Iext/nnstreamer/tensor_filter/584bea7@@nnstreamer_filter_caffe2@sha -Iext/nnstreamer/tensor_filter -I../ext/nnstreamer/tensor_filter -Igst/nnstreamer -I../gst/nnstreamer -Igst/nnstreamer/./include/ -I../gst/nnstreamer/./include/ -I/usr/include/torch -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Werror -std=c++14 '-DVERSION="1.5.2"' -Wredundant-decls -Wwrite-strings -Wformat -Wformat-nonliteral -Wformat-security -Winit-self -Waddress -Wno-multichar -Wvla -Wpointer-arith -DENABLE_TENSORFLOW=1 -DENABLE_TENSORFLOW_LITE=1 -DENABLE_PYTORCH=1 -DENABLE_CAFFE2=1 -DHAVE_ORC=1 -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -pthread -MD -MQ 'ext/nnstreamer/tensor_filter/584bea7@@nnstreamer_filter_caffe2@sha/tensor_filter_caffe2.cc.o' -MF 'ext/nnstreamer/tensor_filter/584bea7@@nnstreamer_filter_caffe2@sha/tensor_filter_caffe2.cc.o.d' -o 'ext/nnstreamer/tensor_filter/584bea7@@nnstreamer_filter_caffe2@sha/tensor_filter_caffe2.cc.o' -c /<<PKGBUILDDIR>>/ext/nnstreamer/tensor_filter/tensor_filter_caffe2.cc
In file included from /usr/include/caffe2/proto/caffe2_pb.h:4:0,
                 from /usr/include/caffe2/core/context_base.h:7,
                 from /usr/include/caffe2/core/context.h:10,
                 from /usr/include/caffe2/core/storage.h:14,
                 from /usr/include/caffe2/core/tensor.h:4,
                 from /usr/include/caffe2/core/blob.h:14,
                 from /usr/include/caffe2/core/workspace.h:15,
                 from /<<PKGBUILDDIR>>/ext/nnstreamer/tensor_filter/tensor_filter_caffe2.cc:36:
/usr/include/caffe2/proto/caffe2.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^~~~~
/usr/include/caffe2/proto/caffe2.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers.  Please
  ^~~~~
/usr/include/caffe2/proto/caffe2.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.
  ^~~~~
```

#### Test case 2

* Caffe2 / Pytorch internally use protobuf v3.8 (force archiving)
* Protobuf v3.8

Both pytorch and caffe2 filter of nnstreamer are built without any errors. All unit tests including caffe2 are passed. 
However, pytorch test cases are failed as below.

```cpp
// ../third_party/protobuf/src/google/protobuf/generated_message_reflection.cc:2321
void AssignDescriptorsImpl(const DescriptorTable* table) {
    ...
    // Fill the arrays with pointers to descriptors and reflection classes.
    const FileDescriptor* file =
        DescriptorPool::generated_pool()->FindFileByName(table->filename);
    GOOGLE_CHECK(file != NULL);
```

**Comment by again4you** [comment]
@kparichay 's [opinion](https://github.com/nnsuite/pytorch/pull/2#issuecomment-636529743)
(I just copied it from pytorch github to maintain a single issue for convenience.)

In my understanding, `BUILD_CUSTOM_PROTOBUF` is `ON` by default, which builds custom protobuf present in this package (from packaging directory containing protobuf 3.6.1). Further, `CAFFE2_LINK_LOCAL_PROTOBUF` is also enabled by default. So, I dont understand why protobuf 3.8 installed in the system should affect pytorch unittest.

Further, as per cmakelists.txt from pytorch/torch, protobuf does not seem to be dependency (not sure though).

Also, pytorch latest versions might not work with protobuf 3.8 (https://github.com/pytorch/pytorch/pull/22437)

**Comment by again4you** [comment]
### Tizen Status
#### Build result & progress
* https://dashboard.tizen.org/index.code?sr=submit%2Ftizen%2F20200703.080932&proj=home%3Aprerelease%3ATizen%3AUnified%3Asubmit%3Atizen%3A20200703.080932&stage=build#build_detail_frame

Only `device-certificate-manager` and `device-certificate-manager-backend` makes a buildbreak.
* Patch is submitted: https://review.tizen.org/gerrit/#/c/platform/core/security/device-certificate-manager/+/237784/

**Comment by kparichay** [comment]
- [ ] Pytorch and Caffe2 version update to latest v1.6.0-rc1 with protobuf v3.12.3 on nnstreamer-launchpad with staging-ppa. Note that version update is only for ubuntu version 18.04 or higher.
- [ ] Updated pytorch and caffe2 version to latest v1.6.0-rc1 on tizen.
- [ ] Patch on nnstreamer to update the Pytorch and Caffe2 extensions with updated version of Pytorch/Caffe2 #2545 
- [ ] Protobuf update to nnstreamer-launchpad with staging-ppa to v3.12.3

**Comment by myungjoo** [comment]
@kparichay Isn't this done? (Close it if it's done)

**Comment by kparichay** [comment]
This is done. However, the updated packages are still in the ppa-staging and haven't moved to the official nnstreamer ppa.

**Comment by again4you** [comment]
Protobuf v3.12.3 is published from the official PPA.
And nnstreamer and required packages are ready to publish the deb packages from the official PPA.

So this issue is going to close.
