### PR TITLE
[android/build] Patch NDK source to prevent build error @open sesame 12/01 15:52

### LINKED ISSUE #2899: Android NDK build error with `AMediaCodecOnAsyncNotifyCallback`
After bumping up the android api level from 24 to 28, following compile error occurs.
Error log:
```
 ...
 [arm64-v8a] Compile        : nnstreamer <= gstamcsrc.c                                                                                                                                                           

  In file included from /home/yongjoo/nnstreamer/ext/nnstreamer/android_source/gstamcsrc.c:74: 
home/yongjoo/android/tools/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/linux-86_64/sysroot/usr/include/media/NdkMediaCodec.h:388:9: error: must use 'struct' tag to refer to type 'AMediaCodecOnAsyncNotifyCallback' 
 AMediaCodecOnAsyncNotifyCallback callback,                                                                                                                                                               
          ^ 
 1 error generated.
  make: *** [/home/yongjoo/nnstreamer/build_android_all/api/build/intermediates/ndkBuild/debug/obj/local/arm64-v8a/objs-debug/nnstreamer//home/yongjoo/nnstreamer/ext/nnstreamer/android_source/gstamcsrc.o] Error 1                                                                                                                                                                                                                 
...
```

Should update the NDK source code after the master branch:
https://android.googlesource.com/platform/frameworks/av/+/master/media/ndk/include/media/NdkMediaCodec.h#117

### PR DESCRIPTION
**Pull request by anyj0527**
- After Android API level 28, the introduced
  `AMediaCodecOnAsyncNotifyCallback` make compile error.
- Make build script to patch this part after
    https://android.googlesource.com/platform/frameworks/av/+/master/media/ndk/include/media/NdkMediaCodec.h#117
- This resolves #2899 

Signed-off-by: Yongjoo Ahn <yongjoo1.ahn@samsung.com>

**Self evaluation:**
1. Build test: [X]Passed [ ]Failed [ ]Skipped
2. Run test: [X]Passed [ ]Failed [ ]Skipped

### CODE REVIEW

File: api/android/build-android-lib.sh [hunk 1]
```diff
@@ -205,6 +205,11 @@ fi
 echo "Android SDK: $android_sdk_dir"
 echo "Android NDK: $android_ndk_dir"
 
+echo "Patching NDK source"
+# See: https://github.com/nnstreamer/nnstreamer/issues/2899
+
+sed -z -i "s|struct AMediaCodecOnAsyncNotifyCallback {\n      AMediaCodecOnAsyncInputAvailable  onAsyncInputAvailable;\n      AMediaCodecOnAsyncOutputAvailable onAsyncOutputAvailable;\n      AMediaCodecOnAsyncFormatChanged   onAsyncFormatChanged;\n      AMediaCodecOnAsyncError           onAsyncError;\n};|typedef struct AMediaCodecOnAsyncNotifyCallback {\n      AMediaCodecOnAsyncInputAvailable  onAsyncInputAvailable;\n      AMediaCodecOnAsyncOutputAvailable onAsyncOutputAvailable;\n      AMediaCodecOnAsyncFormatChanged   onAsyncFormatChanged;\n      AMediaCodecOnAsyncError           onAsyncError;\n} AMediaCodecOnAsyncNotifyCallback;|" $android_ndk_dir/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/media/NdkMediaCodec.h
```
Comment (gichan-jang) [inline api/android/build-android-lib.sh:211]: Is there any problem with other architecture?
Is it okay to apply only x86_64?

Comment (anyj0527) [reply api/android/build-android-lib.sh]: Thanks! After checking https://developer.android.com/ndk/downloads for other host,

I updated
`$android_ndk_dir/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/media/NdkMediaCodec.h`
to
`$android_ndk_dir/toolchains/llvm/prebuilt/*/sysroot/usr/include/media/NdkMediaCodec.h`

**Review by gichan-jang — APPROVED** [review]
LGTM

**Review by dongju-chae — APPROVED** [review]
LGTM
